/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface FarmPoolInterface extends utils.Interface {
  functions: {
    "set_token_addr(address)": FunctionFragment;
    "token_addr()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "set_token_addr", values: [string]): string;
  encodeFunctionData(functionFragment: "token_addr", values?: undefined): string;

  decodeFunctionResult(functionFragment: "set_token_addr", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token_addr", data: BytesLike): Result;

  events: {};
}

export interface FarmPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FarmPoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    set_token_addr(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<ContractTransaction>;

    token_addr(overrides?: CallOverrides): Promise<[string]>;
  };

  set_token_addr(
    addr: string,
    overrides?: Overrides & { from?: string | Promise<string> },
  ): Promise<ContractTransaction>;

  token_addr(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    set_token_addr(addr: string, overrides?: CallOverrides): Promise<void>;

    token_addr(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    set_token_addr(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<BigNumber>;

    token_addr(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    set_token_addr(
      addr: string,
      overrides?: Overrides & { from?: string | Promise<string> },
    ): Promise<PopulatedTransaction>;

    token_addr(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
